name: Run slower pandoc tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Clojure
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: 1.11.3.1463

    - name: Install pandoc binary
      uses: nikeee/setup-pandoc@v1

    - name: Print Pandoc veresion
      run: pandoc --version

    - name: Install dependencies
      run: clojure -e :download-deps

    - name: "Run pandoc tests"
      run: clojure -X:pandoc-tests
